# Uncomment the next line to define a global platform for your project
# platform :ios, '10.0'

target 'ProofWatch_CamiloSoto' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for ProofWatch_CamiloSoto

	pod 'GRDB.swift'

end
